# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: xi4oh4o's diary
email: xi4oh4o@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I love the Internet and programming,
  Currently I work mainly used PHP and Python, but personally I prefer Ruby ❤

  will about tool I like use a OS X and Vim.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://xhs.me" # the base hostname & protocol for your site
twitter_username: XHs
github_username: xi4oh4o
# Build settings
markdown: kramdown
